In [1]:
import torch
from PIL import Image
from transformers import (
    AutoImageProcessor,
    AutoTokenizer,
    AutoModelForCausalLM,
)


model_root = "qihoo360/fg-clip-large"
image_size=336
model = AutoModelForCausalLM.from_pretrained(model_root,trust_remote_code=True)

device = model.device

tokenizer = AutoTokenizer.from_pretrained(model_root)
image_processor = AutoImageProcessor.from_pretrained(model_root)


`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["bos_token_id"]` will be overriden.
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["eos_token_id"]` will be overriden.
Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.


In [2]:
img_root = "053.jpg"
image = Image.open(img_root).convert("RGB")
image = image.resize((image_size,image_size))

image_input = image_processor.preprocess(image, return_tensors='pt')['pixel_values'].to(device)

# NOTE Short captions: max_length=77 && walk_short_pos=True
walk_short_pos = True
captions=["a girl in blue t shirt is sitting next to 2 children in blue t shirts", "a girl in green t shirt is sitting next to 2 children in blue t shirts", "a girl in red t shirt is sitting next to 2 children in blue t shirts"]
caption_input = torch.tensor(tokenizer(captions, max_length=77, padding="max_length", truncation=True).input_ids, dtype=torch.long, device=device)

# NOTE Long captions: max_length=248 && walk_short_pos=False
# ......

with torch.no_grad():
  image_feature = model.get_image_features(image_input)
  text_feature = model.get_text_features(caption_input,walk_short_pos=walk_short_pos)
  image_feature = image_feature / image_feature.norm(p=2, dim=-1, keepdim=True)
  text_feature = text_feature / text_feature.norm(p=2, dim=-1, keepdim=True)

logits_per_image = image_feature @ text_feature.T
logits_per_image = model.logit_scale.exp() * logits_per_image
probs = logits_per_image.softmax(dim=1) 
print(probs)


tensor([[0.4106, 0.3652, 0.2242]], grad_fn=<SoftmaxBackward0>)


In [ ]:
image_feature.shape


torch.Size([1, 768])

In [26]:
text_feature.shape


torch.Size([1, 768])

In [2]:
import torch
from PIL import Image
from transformers import CLIPModel, CLIPImageProcessor, CLIPTokenizer


# =========================
# 1. Cấu hình
# =========================
model_name = "openai/clip-vit-large-patch14"

device = torch.device(
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)

# Chỉ dùng float16 khi chạy CUDA
dtype = torch.float16 if device.type == "cuda" else torch.float32

print("Device:", device)


# =========================
# 2. Load CLIP ViT-L/14
# =========================
model = CLIPModel.from_pretrained(
    model_name,
    torch_dtype=dtype,
    token='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'
).to(device)

model.eval()

image_processor = CLIPImageProcessor.from_pretrained(model_name)
tokenizer = CLIPTokenizer.from_pretrained(model_name)


# =========================
# 3. Load ảnh
# =========================
img_root = "053.jpg"

image = Image.open(img_root).convert("RGB")

# Không cần resize thủ công.
# CLIPImageProcessor sẽ tự resize, center crop và normalize.
image_input = image_processor(
    images=image,
    return_tensors="pt",
)["pixel_values"].to(
    device=device,
    dtype=dtype,
)


# =========================
# 4. Chuẩn bị caption
# =========================
captions = ["a girl in blue t shirt is sitting next to 2 children in blue t shirts", "a girl in green t shirt is sitting next to 2 children in blue t shirts", "a girl in red t shirt is sitting next to 2 children in blue t shirts"]

# CLIP ViT-L/14 sử dụng tối đa 77 token
caption_inputs = tokenizer(
    captions,
    max_length=77,
    padding="max_length",
    truncation=True,
    return_tensors="pt",
)

caption_inputs = {
    key: value.to(device)
    for key, value in caption_inputs.items()
}


# =========================
# 5. Trích xuất feature
# =========================
with torch.inference_mode():
    image_feature = model.get_image_features(
        pixel_values=image_input,
    )

    text_feature = model.get_text_features(
        input_ids=caption_inputs["input_ids"],
        attention_mask=caption_inputs["attention_mask"],
    )

    # L2 normalization
    image_feature = image_feature / image_feature.norm(
        p=2,
        dim=-1,
        keepdim=True,
    )

    text_feature = text_feature / text_feature.norm(
        p=2,
        dim=-1,
        keepdim=True,
    )

    # Cosine similarity
    logits_per_image = image_feature @ text_feature.T

    # Nhân với temperature scale đã học của CLIP
    logits_per_image = model.logit_scale.exp() * logits_per_image

    # Xác suất tương đối giữa các caption
    probs = logits_per_image.softmax(dim=-1)


# =========================
# 6. In kết quả
# =========================
print("\nRaw logits:")
print(logits_per_image.cpu())

print("\nProbabilities:")
print(probs.cpu())

print("\nRanking:")

ranking = torch.argsort(
    probs[0],
    descending=True,
)

for rank, index in enumerate(ranking.tolist(), start=1):
    probability = probs[0, index].item()

    print(
        f"{rank}. {probability:.4%} | "
        f"{captions[index]}"
    )

best_index = probs.argmax(dim=-1).item()

print("\nBest caption:")
print(captions[best_index])


Device: mps

Raw logits:
tensor([[21.2651, 21.2803, 20.8449]])

Probabilities:
tensor([[0.3742, 0.3799, 0.2458]])

Ranking:
1. 37.9944% | a girl in green t shirt is sitting next to 2 children in blue t shirts
2. 37.4227% | a girl in blue t shirt is sitting next to 2 children in blue t shirts
3. 24.5829% | a girl in red t shirt is sitting next to 2 children in blue t shirts

Best caption:
a girl in green t shirt is sitting next to 2 children in blue t shirts
